###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

  mysql:
    image: mysql:8
    container_name: parnassys-mysql
    working_dir: /application
    
    volumes:
      - .:/application
      - ./mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=demoSecure!
      - MYSQL_DATABASE=demodb
      - MYSQL_USER=demo
      - MYSQL_PASSWORD=demo
    ports:
      - "8336:3306"

  php:
    build: ./docker_files/docker_symfony
    container_name: parnassys-php
    working_dir: /application
    volumes:
      - ./symfony_app:/application
      - ./docker_files/docker_symfony/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini
      - ./docker_files/docker_symfony/z-overrides.conf:/etc/php/8.2/fpm/pool.d/z-overrides.conf
